### PR TITLE
FLA-1163 - Add audit user to mongo table

### PR DESCRIPTION
**Pull request by BrianMaki**
# Description

This PR includes the following proposed change(s):

- FLA-1163
- Add createdBy and lastModifiedBy fields to Auditable
- Populated createdBy and lastModifiedBy from security token via SecurityUtils => MongoAuditorAware => AuditConfig

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Existing unit test via DocumentConfigurationsEventListenerTest and Postman for Create Document Type Configuration, Update Document Type Configuration and Delete Document Type Configuration.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by BrianMaki** [comment]
Mongo table results:

Screen Shot 2021-05-24 at 10 00 47 AM

**Comment by BrianMaki** [comment]
Mongo table results:

Screen Shot 2021-05-24 at 7 10 23 PM

**Review by TayGov — APPROVED** [review]
👍

**Comment by KDNeufeld** [comment]
Well done Brian.  Nice and clean.

**Pull request merged**
